services:
  influxdb:
    image: influxdb:2.6
    container_name: monitoring-influxdb-1
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks: [monnet]

  grafana:
    image: grafana/grafana:10.4.2
    container_name: monitoring-grafana-1
    ports:
      - "8081:3000"       # чтобы не конфликтовать с чем-то на 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    networks: [monnet]

  telegraf:
    image: telegraf:1.30
    container_name: monitoring-telegraf-1
    depends_on: [influxdb, stub]
    networks: [monnet]
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  stub:
    build:
      context: ./stub
      dockerfile: Dockerfile
    image: monitoring-stub:latest
    container_name: monitoring-stub-1
    ports:
      - "8080:8080"
    networks: [monnet]

networks:
  monnet:

volumes:
  influxdb-data: