[agent]
  interval = "5s"
  round_interval = true
  flush_interval = "5s"
  omit_hostname = true

# Скрейп Spring Actuator Prometheus endpoint
[[inputs.prometheus]]
  urls = ["http://stub:8080/actuator/prometheus"]
  metric_version = 2         # важно! даёт формат с __name__ и тэгами

# Пишем в InfluxDB v2
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "admintoken"
  organization = "myorg"
  bucket = "mybucket"